name: CICD pipeline For Testing We will print content of hello.txt

on:
    push:
       branches:
            - main

jobs:

    job1:
        runs-on: ubuntu-latest
        steps:
            - name: print Hello World
              run: echo "hello world"